### PR TITLE
Gregoan osb soa

### PR DESCRIPTION
**Pull request by gregoan**

### CODE REVIEW

**Comment by ccristian** [comment]
Will start working on these conflicts.your branch is stable ? All these new additions work ?

**Comment by gregoan** [comment]
Hi,

I would like to say yes but I wanted first to know if it was making sense to get nodata to « false ».
I’m not asking you to debug my changes ; as I said, I can restart from your build and proceed step by step but before to do that, I wanted to know if you had an idea about the no graph generation (and nodata value).

Alain.

**Comment by ccristian** [comment]
That flag is set to false and is used to get all the resources without data so I cab build the UI.

For example : 
I want the interval from 1.09.2016 to 30.09.2016 .Previously we did a rest to get the whole data in one shot.Might be to much for some admin servers especially where are multiple managed servers.

So now the data is fetched per/day so 1 , 2, 3, 4.......etc
Now it is possible to have the case that a certain JMS resource appears only on 4.09 so in order to avoid complicated logic on UI before calling each data / day ....i do a call for the whole interval to get the structure of the existing resources and then I iterate day by day and fill in the graphs.

Cristian

**Comment by gregoan** [comment]
I will start again from your version and will contact you if needed.

Alain.

**Comment by ccristian** [comment]
I can gladly help and sorry for letting this suspended for a while....

For getting the data / day you used the flag set to true....is used only once with false to 'init' the UI  let's say

**Comment by gregoan** [comment]
Cancelled

**Pull request closed without merging**
